# Generated by Django 4.2.9 on 2024-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_articles_options_articles_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='review_type',
            field=models.IntegerField(default=0, verbose_name='review_type'),
        ),
    ]
