# Generated by Django 4.2.9 on 2024-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_articles_review_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img_route',
            field=models.CharField(default='', max_length=200, verbose_name='img_route'),
        ),
    ]
