# Generated by Django 4.2.9 on 2024-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_articles_img_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(default='', verbose_name='tresc'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default='', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='rating',
            field=models.IntegerField(default='', verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='review_type',
            field=models.IntegerField(default='', verbose_name='review_type'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='nazwa'),
        ),
    ]
